name: Test reusable environment

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - run: echo "${{ github.ref_name }}"
      - run: echo "${{ secrets.ENV_SEC }}"
