name: Test reusable environment

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [dev, prod]
    environment: ${{ matrix.target }}
    steps:
      - run: echo "${{ matrix.target }}"
      - run: echo "${{ secrets.ENV_SEC }}"